services:
  - type: web
    name: telegram-inventory-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        fromEnvVar: BOT_TOKEN
      - key: ADMIN_ID
        fromEnvVar: ADMIN_ID
